services:
  - type: web
    name: chatbot
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"